import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { MessageSquare, Phone, Mail, FileText, Plus, Send, StickyNote, Clock } from 'lucide-react';
import { MOCK_COMMUNICATIONS } from '@/data/mockData';
import type { CaseCommunication } from '@/types/sleq';

const TYPE_ICONS: Record<string, React.ReactNode> = {
  EMAIL_SENT: <Mail className="w-3.5 h-3.5 text-blue-500" />,
  EMAIL_RECEIVED: <Mail className="w-3.5 h-3.5 text-emerald-500" />,
  PHONE_CALL: <Phone className="w-3.5 h-3.5 text-amber-500" />,
  NOTE: <StickyNote className="w-3.5 h-3.5 text-purple-500" />,
  DOCUMENT_REQUEST: <FileText className="w-3.5 h-3.5 text-orange-500" />,
  FOLLOW_UP: <Clock className="w-3.5 h-3.5 text-info" />,
  STATUS_UPDATE: <Send className="w-3.5 h-3.5 text-primary" />,
  AUTO: <MessageSquare className="w-3.5 h-3.5 text-muted-foreground" />,
};

const DIR_COLORS: Record<string, string> = {
  INBOUND: 'bg-emerald-100 text-emerald-800',
  OUTBOUND: 'bg-blue-100 text-blue-800',
  INTERNAL: 'bg-purple-100 text-purple-800',
};

export default function CommunicationLog() {
  const [showAdd, setShowAdd] = useState(false);
  const [addType, setAddType] = useState('PHONE_CALL');
  const comms = [...MOCK_COMMUNICATIONS].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());

  return (
    <div className="p-6 lg:p-8 space-y-5 max-w-[1000px]">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-foreground">Communication Log</h1>
          <p className="text-sm text-muted-foreground mt-1">Midwest Manufacturing Corp — Case #24001</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" className="gap-1" onClick={() => { setAddType('PHONE_CALL'); setShowAdd(true); }}><Phone className="w-3.5 h-3.5" /> Log Call</Button>
          <Button variant="outline" size="sm" className="gap-1" onClick={() => { setAddType('EMAIL_SENT'); setShowAdd(true); }}><Mail className="w-3.5 h-3.5" /> Log Email</Button>
          <Button variant="outline" size="sm" className="gap-1" onClick={() => { setAddType('NOTE'); setShowAdd(true); }}><StickyNote className="w-3.5 h-3.5" /> Internal Note</Button>
        </div>
      </div>

      {/* Timeline */}
      <div className="space-y-3">
        {comms.map(c => (
          <Card key={c.id} className="border shadow-sm">
            <CardContent className="p-4">
              <div className="flex items-start gap-3">
                <div className="mt-0.5">{TYPE_ICONS[c.commType]}</div>
                <div className="flex-1 space-y-1">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="text-xs font-medium text-foreground">{new Date(c.createdAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}</span>
                    <Badge className={`text-[10px] ${DIR_COLORS[c.direction]}`}>{c.direction}</Badge>
                    {c.contactName && <span className="text-xs text-muted-foreground">— {c.contactName}</span>}
                    {c.isAutoGenerated && <Badge variant="outline" className="text-[10px]">Auto</Badge>}
                  </div>
                  <p className="text-sm font-medium text-foreground">{c.subject}</p>
                  <p className="text-xs text-muted-foreground">{c.body}</p>
                  {c.attachments && c.attachments.length > 0 && (
                    <div className="flex items-center gap-1 mt-1">
                      <FileText className="w-3 h-3 text-muted-foreground" />
                      {c.attachments.map(a => <span key={a} className="text-[10px] text-primary underline">{a}</span>)}
                    </div>
                  )}
                  {c.linkedStepId && (
                    <p className="text-[10px] text-muted-foreground">🔗 Linked to {c.linkedStepId}</p>
                  )}
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Add Dialog */}
      <Dialog open={showAdd} onOpenChange={setShowAdd}>
        <DialogContent>
          <DialogHeader><DialogTitle>Log Communication</DialogTitle></DialogHeader>
          <div className="space-y-3">
            <div className="grid grid-cols-2 gap-2">
              <div className="space-y-1">
                <Label className="text-xs">Type</Label>
                <Select value={addType} onValueChange={setAddType}>
                  <SelectTrigger className="text-xs"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    {['PHONE_CALL', 'EMAIL_SENT', 'EMAIL_RECEIVED', 'NOTE', 'FOLLOW_UP', 'DOCUMENT_REQUEST'].map(t => (
                      <SelectItem key={t} value={t}>{t.replace(/_/g, ' ')}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-1">
                <Label className="text-xs">Contact Name</Label>
                <Input placeholder="Jane Smith" />
              </div>
            </div>
            <div className="space-y-1">
              <Label className="text-xs">Subject</Label>
              <Input placeholder="Subject..." />
            </div>
            <div className="space-y-1">
              <Label className="text-xs">Details</Label>
              <Textarea rows={3} placeholder="Communication details..." />
            </div>
          </div>
          <DialogFooter><Button onClick={() => setShowAdd(false)}>Save Entry</Button></DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
